const image='/images/reference-hero.png';
const entries=[{id:'kodo',type:'OBJECTS',title:'KŌDŌ',jp:'香道',desc:'The ritual of incense listening.',place:'KYOTO, JAPAN',date:'07.08.2026',tags:['ritual','incense','sensory']},{id:'fushimi-inari',type:'PLACES',title:'FUSHIMI INARI',jp:'伏見稲荷',desc:'A mountain path of repeating vermilion gates.',place:'KYOTO, JAPAN',date:'05.08.2026',tags:['shrine','architecture','kyoto']},{id:'washi',type:'CRAFT',title:'WASHI',jp:'和紙',desc:'Paper that carries light.',place:'GIFU, JAPAN',date:'01.08.2026',tags:['paper','craft','material']},{id:'tea-bowl',type:'OBJECTS',title:'TEA BOWL',jp:'茶碗',desc:'A handmade object for a quiet moment.',place:'SHIGARAKI, JAPAN',date:'28.07.2026',tags:['tea','ceramics','wabi-sabi']},{id:'sagano',type:'PLACES',title:'SAGANO',jp:'嵯峨野',desc:'Where the wind moves softly through bamboo.',place:'KYOTO, JAPAN',date:'21.07.2026',tags:['landscape','bamboo','kyoto']},{id:'kyoto',type:'PLACES',title:'KYOTO',jp:'京都',desc:'A city where old forms keep changing shape.',place:'KYOTO, JAPAN',date:'18.07.2026',tags:['city','architecture','culture']}];
const cats=['ALL','OBJECTS','PLACES','CRAFT','ART','PEOPLE','IDEAS'];
const saved=()=>JSON.parse(localStorage.getItem('serendipity-saved')||'[]');
const header=()=>`<header class="header"><a class="monogram" href="/">S.</a><nav class="nav"><a href="/archive/">ARCHIVE</a><a href="/journal/">JOURNAL</a><a href="/collection/">COLLECTION</a><a href="/about/">ABOUT</a></nav><a class="search-trigger" href="/search/">SEARCH <span class="search-dot"></span></a></header>`;
const footer=()=>`<footer class="footer"><div class="footer-title">SERENDIPITY</div><div class="footer-manifesto">A DIGITAL ARCHIVE<br>OF THINGS WORTH FINDING.</div><div class="footer-links"><a href="/archive/">ARCHIVE</a><a href="/journal/">JOURNAL</a><a href="/collection/">COLLECTION</a><a href="/about/">ABOUT</a></div><div class="footer-meta">TOKYO · KYOTO · SHANGHAI · SEOUL<br>© 2026 SERENDIPITY</div></footer>`;
function card(e,i=0){return `<article class="archive-item item-${i%3}"><div class="entry-meta"><span>${String(i+1).padStart(2,'0')}</span><span class="red">${e.type}</span></div><a class="entry-image" href="/object/${e.id}/"><img src="${image}" alt=""><span class="save">${saved().includes(e.id)?'♥':'♡'}</span></a><div class="entry-copy"><h3>${e.title}</h3><span class="jp">${e.jp}</span><p>${e.desc}</p><small>${e.place} · ${e.date}</small></div></article>`}
function archive(){const q=new URLSearchParams(location.search).get('category')||'all';const list=q==='all'?entries:entries.filter(e=>e.type.toLowerCase()===q);return `<main class="site-shell">${header()}<section class="page-head"><span class="eyebrow">SERENDIPITY / INDEX</span><h1>THE <em>ARCHIVE</em></h1><p>Objects, places, craft, people and ideas collected for closer looking.</p></section><div class="archive-page-toolbar"><div class="categories">${cats.map(c=>`<a class="${q===c.toLowerCase()?'active':''}" href="/archive/?category=${c.toLowerCase()}">${c}</a>`).join('')}</div><a class="text-link" href="/search/">SEARCH ARCHIVE <span>→</span></a></div><section class="archive archive-page-grid"><div class="archive-grid">${list.map(card).join('')}</div></section>${footer()}</main>`}
function detail(){const id=location.pathname.split('/')[2];const e=entries.find(x=>x.id===id)||entries[0];return `<main class="site-shell">${header()}<article class="detail"><div class="detail-meta"><span class="red">${e.type}</span><span>${e.place}</span><span>${e.date}</span></div><div class="detail-grid"><div class="detail-image"><img src="${image}" alt="${e.title}"></div><div class="detail-copy"><span class="jp">${e.jp}</span><h1>${e.title}</h1><p class="detail-lead">${e.desc}</p><p>This entry is part of Serendipity's working archive: a place to record the context, material, ritual and small details that make an ordinary subject worth returning to.</p><div class="tag-list">${e.tags.map(t=>`<a href="/search/?q=${encodeURIComponent(t)}">#${t}</a>`).join('')}</div></div></div><div class="detail-essay"><span class="eyebrow">FIELD NOTE</span><p>Look at the subject again after the first impression. Notice the edge, the material, the hand that made it, and the relationship between the thing and the space around it.</p></div></article>${footer()}</main>`}
function journal(){return `<main class="site-shell">${header()}<section class="page-head"><span class="eyebrow">JOURNAL / ESSAYS</span><h1>WORDS TO<br><em>LOOK THROUGH</em></h1><p>Longer notes about objects, places, craft and the cultures around them.</p></section><section class="journal-list"><a class="journal-feature" href="/journal/why-japanese-objects-feel-different/"><img src="${image}" alt=""><div><span class="eyebrow">12 MIN READ · JAPAN · CRAFT</span><h2>Why Japanese objects feel different</h2><p>An essay about quiet intention, imperfect materials and the beauty of things made by human hands.</p><span class="text-link">READ ESSAY →</span></div></a></section>${footer()}</main>`}
function story(){return `<main class="site-shell">${header()}<article class="story"><div class="story-top"><span class="eyebrow">ESSAY · 12 MIN READ · 08.08.2026</span><h1>WHY JAPANESE<br>OBJECTS FEEL<br><em>DIFFERENT</em></h1><p>An essay about quiet intention, imperfect materials and the beauty of things made by human hands.</p></div><div class="story-image"><img src="${image}" alt=""></div><div class="story-body"><p>There are objects that ask to be looked at, and objects that teach you how to look. Japanese craft often becomes memorable through the second category.</p><p>A tea bowl, a sheet of paper, a wooden tray or a small incense vessel does not need visual perfection to feel resolved. Surface, proportion and the evidence of making carry the story.</p><p>The interesting detail is usually one you notice after the first impression: a thumb mark, a repair, a slight asymmetry, the way an edge catches light.</p></div></article>${footer()}</main>`}
function discover(){const e=entries[Math.floor(Math.random()*entries.length)];return `<main class="site-shell">${header()}<section class="discovery"><span class="eyebrow">SERENDIPITY / RANDOM FIND</span><h1>YOU WEREN'T<br><em>LOOKING</em><br>FOR THIS.</h1><div class="discovery-card">${card(e)}</div><a class="discover-large" href="/discover/?n=${Date.now()}">ANOTHER FIND <span>→</span></a></section>${footer()}</main>`}
function collection(){const list=entries.filter(e=>saved().includes(e.id));return `<main class="site-shell">${header()}<section class="page-head"><span class="eyebrow">YOUR COLLECTION</span><h1>${String(list.length).padStart(2,'0')} <em>SAVED</em></h1><p>A personal trail through the archive.</p></section><section class="archive"><div class="archive-grid">${list.length?list.map(card).join(''):'<div class="empty">NOTHING SAVED YET. RETURN TO THE ARCHIVE AND KEEP WHAT CATCHES YOUR EYE.</div>'}</div></section>${footer()}</main>`}
function search(){const q=new URLSearchParams(location.search).get('q')||'';const list=q?entries.filter(e=>`${e.title} ${e.jp} ${e.desc} ${e.place} ${e.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase())):entries;return `<main class="site-shell">${header()}<section class="page-head"><span class="eyebrow">SEARCH</span><h1>FIND A <em>TRACE</em></h1><form class="search-big"><input name="q" value="${q.replaceAll('"','&quot;')}" placeholder="Kyoto, tea, craft..."><button>SEARCH</button></form><p>${q?`${list.length} findings for “${q}”`:'Search across objects, places, craft and ideas.'}</p></section><section class="archive"><div class="archive-grid">${list.map(card).join('')}</div></section>${footer()}</main>`}
function about(){return `<main class="site-shell">${header()}<section class="about about-page"><div class="about-label">THE PROJECT</div><div><span class="eyebrow">SERENDIPITY / DIGITAL ARCHIVE</span><h1>WE LOOK<br><em>CLOSER.</em></h1><p>Serendipity is a visual archive of things worth finding: objects, places, craft, people and ideas that reward a second look.</p><p>The site is designed less like a news feed and more like a cabinet of curiosities. Every entry should have enough context to become a starting point for another discovery.</p></div></section>${footer()}</main>`}
function render(){const p=location.pathname.replace(/\/+$/,'')||'/';let html=archive();if(p==='/journal')html=journal();else if(p==='/collection')html=collection();else if(p==='/discover')html=discover();else if(p==='/search')html=search();else if(p==='/about')html=about();else if(p==='/journal/why-japanese-objects-feel-different')html=story();else if(p.startsWith('/object/'))html=detail();document.querySelector('#app').innerHTML=html}
render();
